### ISSUE TITLE
Create XHR functions

### ISSUE THREAD

**Issue by mjleavell** [nss-evening-cohort-8/chatty-spatulas#16]
# User Story
As a user, when the app loads, it should work. 

# Acceptance Criteria
* The application should work as expected.

# Tech Notes
* XHR request to the startupMsg.json file to populate to the 5 initial messages.
* success funciton, error function, and getMsgData function should be place in startupData.js
* create empty messagesArray to hold messages that we print (similar to pets and thrones)
* create msgBuilder function that creates domString from messagesArray on chattyMsg.js
** Username in Bold, timestamp, and message
* import msgBuilder functions from chattyMsg.js to navbarEvents.js

**Comment by MCrank** [comment]
Sample Message Build for DOM message layout
```html
<div id="messageId">
    <h5>9/10/2018 12:00:00<strong>Marco</strong></h5>
    <p>Four Score and Seven Years Ago</p>
    <input type="button" value="delete">
    <input type="button" value="edit">
</div>
