### ISSUE TITLE
Event Listener for NavBar (Clear)

### ISSUE THREAD

**Issue by MCrank** [nss-evening-cohort-8/chatty-spatulas#20]
# User Story
As a user, I want the ability to clear all messages in the message box. 

# Acceptance Criteria
* When I click the clear button, all messages should be cleared from the message-output div

# Technical Notes
* add Clear Message button on index.html
* import printToDom from util.js if not already done
* create empty messagesArray to hold messages that we print (similar to pets and thrones)
* create clearMsg function (set innerHTML set to empty string) on chattyMsg.js
* Ensure the clearMsg function empties out the messagesArray as well as clear the DOM so we do not repopulate the old list with the next entered message.
* import clearMsg functions from chattyMsg.js to navbarEvents.js
* create clearMsgEvent event listener (click) on the clear button on navbarEvents.js that calls clearMsg function
* Clear button should be disabled if no messages are in the messagesArray

**Comment by mjleavell** [comment]
![image](https://user-images.githubusercontent.com/42177496/46702991-e46dff80-cbea-11e8-9dde-f397501813fb.png)

**Comment by mjleavell** [comment]
![image](https://user-images.githubusercontent.com/42177496/46705023-43377700-cbf3-11e8-809e-d1873e4ab5f2.png)
