### ISSUE TITLE
Event Listener - Delete Message

### ISSUE THREAD

**Issue by mjleavell** [nss-evening-cohort-8/chatty-spatulas#23]
# User Story
As a user, when I click the delete button on an existing message, the message should be removed. 

# Acceptance Criteria
**When** the delete button is clicked on an existing message
**Then** the message's object should be removed from the messages array
**And** the updated array should be printed

# Technical Notes
* create deleteBtnEvent on msgEvents.js that add eventListener to delete button
* get the id of the individual message you want to delete 
* use the .remove method inside the deleteMsg(id) function on chattyMsg.js to remove message.

**Comment by MCrank** [comment]
Merged PR #60
