### ISSUE TITLE
Create Username object in javascript

### ISSUE THREAD

**Issue by mjleavell** [nss-evening-cohort-8/chatty-spatulas#26]

**Comment by mjleavell** [comment]
Not entirely sure why we dont add this to #15 when we create object? seems silly to got back and edit later.

**Comment by MCrank** [comment]
I think the intent here was this was a feature request that comes in after the initial app build.  i.e. we should treat it as a request that comes in at a later date forcing us to update the app and not break it at the same time.  @zoeames @morecallan  Is this correct?

**Comment by mjleavell** [comment]
closing this item because adding to #15
