### ISSUE TITLE
Event Listener - Enter Key

### ISSUE THREAD

**Issue by MCrank** [nss-evening-cohort-8/chatty-spatulas#27]

**Comment by MCrank** [comment]
@mjleavell Do you recall what this one was for?  I think I left off some important information for this card?

**Comment by mjleavell** [comment]
@MCrank I think this the enter key event listener that calls the messageBuilder function but i think this was covered in #19. I think the original plan was to console log message for card #19 and then actually print it to to page in this ticket.  I think we can close this ticket.

**Comment by MCrank** [comment]
@mjleavell Okay I'll close for now and we can re-add if it reappears.  👍
