### ISSUE TITLE
Add Dark Theme Checkbox

### ISSUE THREAD

**Issue by lancehamilton24** [nss-evening-cohort-8/chatty-spatulas#28]
### User Experience
As a user, when I click on the dark theme button I want the background color to turn gray and the text color should change to white. 

### Acceptance Criteria
* Checkbox labeled "Dark theme"
* Background color should change to gray and text color should be white when user selects "Dark theme" checkbox. 
* Background color should change back to white and text back to black when user unselects "Dark theme" checkbox. 

### Technical Notes
* Create and export darkTheme function in navbarEvents.js
* Create and export lightTheme function in navbarEvents.js
* Target whole body to change background and text color of entire page.

**Comment by mjleavell** [comment]
![image](https://user-images.githubusercontent.com/42177496/46702862-63166d00-cbea-11e8-9919-53fc99acc00a.png)

**Comment by mjleavell** [comment]
closing this ticket because not doing it. achieved in #32
