### ISSUE TITLE
Add large text checkbox in change theme modal

### ISSUE THREAD

**Issue by lancehamilton24** [nss-evening-cohort-8/chatty-spatulas#29]
### User Story
As a user, when I select the "Large text" button, I want all text in the chat conversation to enlarge. 

### Acceptance Criteria
* Checkbox below the message input field labeled "Large text"
* When checked, the text size in the chat conversation should increase

### Technical Notes
* Create and export largeText function in navbarEvents.js
* target message-output in index.html in order to replace all text.

**Comment by mjleavell** [comment]
![image](https://user-images.githubusercontent.com/42177496/46705402-fe144480-cbf4-11e8-987f-c0f953f27d12.png)
