### ISSUE TITLE
Add change site settings button to UI

### ISSUE THREAD

**Issue by MCrank** [nss-evening-cohort-8/chatty-spatulas#32]
# User Story
As a user, I would like to choose from different colors for my background and text
# Acceptance Criteria
I should have an option in place of just the "dark theme" check box that gives me multiple options for a bcakground color and text color when I hit the "save"button
# Tech Notes
* remove the "Dark" theme check box
* Add a bootstrap element such as a "Choose Theme" button that opens a Modal
* in the Modal ther should be 2 color pickers one for background and one for text
* and a "save" and "cancel" button on the modal.

**Comment by mjleavell** [comment]
![image](https://user-images.githubusercontent.com/42177496/46705413-08ced980-cbf5-11e8-815f-b15708aa9ca0.png)
