### ISSUE TITLE
Clear Messages Button Disabled after messages deleted

### ISSUE THREAD

**Issue by mjleavell** [nss-evening-cohort-8/chatty-spatulas#67]
# User Story
As a user, when I delete all of the messages in the message output, I want the clear button to be disabled.

# Acceptance Criteria
**When** I delete all of the messages
**Then** the clear messages button should be disabled

# Tech Notes
* add disable button to deleteMsg function

**Comment by lancehamilton24** [comment]
👍  Looks good!!

**Comment by MCrank** [comment]
👍 Not sure if this is a new bug or not but when I add a new message after emptying the messages the Clear Message button does not re-enable.
